<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Assignment #1</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="assignment_1_files/libs/clipboard/clipboard.min.js"></script>
<script src="assignment_1_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="assignment_1_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="assignment_1_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="assignment_1_files/libs/quarto-html/popper.min.js"></script>
<script src="assignment_1_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="assignment_1_files/libs/quarto-html/anchor.min.js"></script>
<link href="assignment_1_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="assignment_1_files/libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="assignment_1_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="assignment_1_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="assignment_1_files/libs/bootstrap/bootstrap-9e3ffae467580fdb927a41352e75a2e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Assignment #1</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(data.table)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(seqminer)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(HardyWeinberg)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="assignment-1" class="level2">
<h2 class="anchored" data-anchor-id="assignment-1">Assignment 1</h2>
<p>You only need to write lines of code for each question. When answering questions that ask you to identify or interpret something, the length of your response doesn’t matter. For example, if the answer is just ‘yes,’ ‘no,’ or a number, you can just give that answer without adding anything else.</p>
<p>We will go through comparable code and concepts in the live learning session. If you run into trouble, start by using the help help() function in R, to get information about the datasets and function in question. The internet is also a great resource when coding (though note that no outside searches are required by the assignment!). If you do incorporate code from the internet, please cite the source within your code (providing a URL is sufficient).</p>
<p>Please bring questions that you cannot work out on your own to office hours, work periods or share with your peers on Slack. We will work with you through the issue.</p>
<p>You will need to install PLINK and run the analyses. Please follow the OS-specific setup guide in <a href="../../SETUP.md"><code>SETUP.md</code></a>. PLINK is a free, open-source whole genome association analysis toolset, designed to perform a range of basic, large-scale analyses in a computationally efficient manner.</p>
<section id="question-1-data-inspection" class="level4">
<h4 class="anchored" data-anchor-id="question-1-data-inspection">Question 1: Data inspection</h4>
<p>Before fitting any models, it is essential to understand the data. Use R or bash code to answer the following questions about the <code>gwa.qc.A1.fam</code>, <code>gwa.qc.A1.bim</code>, and <code>gwa.qc.A1.bed</code> files, available at the following Google Drive link: <a href="https://drive.google.com/drive/folders/11meVqGCY5yAyI1fh-fAlMEXQt0VmRGuz?usp=drive_link" class="uri">https://drive.google.com/drive/folders/11meVqGCY5yAyI1fh-fAlMEXQt0VmRGuz?usp=drive_link</a>. Please download all three files from this link and place them in <code>02_activities/data/</code>.</p>
<ol type="i">
<li>Read the .fam file. How many samples does the dataset contain?</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wc</span> <span class="at">--lines</span> ./02_activities/data/gwa.qc.A1.fam</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>4000 ./02_activities/data/gwa.qc.A1.fam</code></pre>
</div>
</div>
</section>
</section>
<section id="your-answer-here" class="level1">
<h1>Your answer here…</h1>
<pre><code>4000 samples

(ii) What is the 'variable type' of the response variable (i.e.Continuous or binary)?


# Your answer here...</code></pre>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="bu">pwd</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span> ./02_activities/data/gwa.qc.A1.fam</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>/c/Users/amand/OneDrive - Dalhousie University/Desktop/DSI Course/gen_data
0   A2001   0   0   1   -0.694438129641973
1   A2002   0   0   1   1.85384536141856
2   A2003   0   0   1   2.08263677761584
3   A2004   0   0   1   2.73871473943968
4   A2005   0   0   1   1.34114035564636
5   A2006   0   0   1   0.416778586749647
6   A2007   0   0   1   2.38297123290054
7   A2008   0   0   1   1.51429928826958
8   A2009   0   0   1   0.718686390529039
9   A2010   0   0   1   2.08904136245205</code></pre>
</div>
</div>
<pre><code>Continuous variable type.

(iii) Read the .bim file. How many SNPs does the dataset contain?
</code></pre>
</section>
<section id="your-answer-here-1" class="level1">
<h1>Your answer here…</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span> ./02_activities/data/gwa.qc.bim</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">wc</span> <span class="at">--lines</span> ./02_activities/data/gwa.qc.A1.bim</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>head: cannot open './02_activities/data/gwa.qc.bim' for reading: No such file or directory
101083 ./02_activities/data/gwa.qc.A1.bim</code></pre>
</div>
</div>
<p>There are 101083 SNPs.</p>
<section id="question-2-allele-frequency-estimation" class="level4">
<h4 class="anchored" data-anchor-id="question-2-allele-frequency-estimation">Question 2: Allele Frequency Estimation</h4>
<ol type="i">
<li>Load the genotype matrix for SNPs rs1861, rs3813199, rs3128342, and rs11804831 using additive coding. What are the allele frequencies (AFs) for these four SNPs?</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="bu">printf</span> <span class="st">"%s\n"</span> rs1861 rs3813199 rs3128342 rs11804831 <span class="op">&gt;</span> ./02_activities/data/snplist.txt</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="ex">plink2</span> <span class="at">--bfile</span> ./02_activities/data/gwa.qc.A1 <span class="dt">\</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>      <span class="at">--extract</span> ./02_activities/data/snplist.txt <span class="dt">\</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">--freq</span> <span class="at">--out</span> ./02_activities/data/gwa_qc_A1_freq</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>freq <span class="ot">&lt;-</span> <span class="fu">fread</span>(<span class="st">"./02_activities/data/gwa_qc_A1_freq.afreq"</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(freq)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   #CHROM         ID    REF    ALT PROVISIONAL_REF? ALT_FREQS OBS_CT
    &lt;int&gt;     &lt;char&gt; &lt;char&gt; &lt;char&gt;           &lt;char&gt;     &lt;num&gt;  &lt;int&gt;
1:      1  rs3813199      G      A                Y 0.0569126   7942
2:      1 rs11804831      T      C                Y 0.1543410   7924
3:      1  rs3128342      C      A                Y 0.3051210   7928
4:      1     rs1861      C      A                Y 0.0539859   7928</code></pre>
</div>
</div>
<p>All of these allele frequencies are below 0.5, which means they represent the minor allele frequencies for these SNPs.</p>
<p>Therefore, the major allele frequencies are:</p>
<p>rs1861: 1-0.0539859=0.9460141, rs3813199:1-0.0569126=0.9430874, rs3128342:1-0.305121=0.694879, rs11804831: 1-0.154341=0.845659</p>
<ol start="2" type="i">
<li>What are the minor allele frequencies (MAFs) for these four SNPs? #From the frequencies calculated in the previous code, the minor allele frequencies are: rs1861: 0.0539859, rs3813199:0.0569126, rs3128342:0.305121, rs11804831: 0.154341</li>
</ol>
</section>
<section id="question-3-hardyweinberg-equilibrium-hwe-test" class="level4">
<h4 class="anchored" data-anchor-id="question-3-hardyweinberg-equilibrium-hwe-test">Question 3: Hardy–Weinberg Equilibrium (HWE) Test</h4>
<ol type="i">
<li>Conduct the Hardy–Weinberg Equilibrium (HWE) test for all SNPs in the .bim file. Then, load the file containing the HWE p-value results and display the first few rows of the resulting data frame.</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="ex">plink2</span> <span class="at">--bfile</span> ./02_activities/data/gwa.qc.A1 <span class="at">--hardy</span> <span class="at">--out</span> ./02_activities/data/gwa_qc_A1_hwe</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>hwe <span class="ot">&lt;-</span> <span class="fu">fread</span>(<span class="st">"./02_activities/data/gwa_qc_A1_hwe.hardy"</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(hwe)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   #CHROM         ID     A1     AX HOM_A1_CT HET_A1_CT TWO_AX_CT O(HET_A1)
    &lt;int&gt;     &lt;char&gt; &lt;char&gt; &lt;char&gt;     &lt;int&gt;     &lt;int&gt;     &lt;int&gt;     &lt;num&gt;
1:      1  rs3737728      G      A      1713      1841       428  0.462330
2:      1  rs1320565      C      T      3368       589        19  0.148139
3:      1  rs3813199      G      A      3531       428        12  0.107781
4:      1 rs11804831      T      C      2820      1061        81  0.267794
5:      1  rs3766178      T      C      2391      1378       214  0.345970
6:      1  rs3128342      C      A      1927      1655       382  0.417508
   E(HET_A1)         P
       &lt;num&gt;     &lt;num&gt;
1:  0.447932 0.0437892
2:  0.145262 0.2734290
3:  0.107347 1.0000000
4:  0.261040 0.1133540
5:  0.350629 0.4158770
6:  0.424044 0.3302730</code></pre>
</div>
</div>
<ol start="2" type="i">
<li>What are the HWE p-values for SNPs rs1861, rs3813199, rs3128342, and rs11804831?</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="ex">plink2</span> <span class="at">--bfile</span> ./02_activities/data/gwa.qc.A1 <span class="dt">\</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>      <span class="at">--extract</span> ./02_activities/data/snplist.txt <span class="dt">\</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">--hardy</span> <span class="at">--out</span> ./02_activities/data/gwa_qc_A1_hwe_snplist</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>PLINK v2.0.0-a.7 64-bit (10 Jan 2026)               cog-genomics.org/plink/2.0/
(C) 2005-2026 Shaun Purcell, Christopher Chang    GNU General Public License v3
Logging to ./02_activities/data/gwa_qc_A1_hwe_snplist.log.
Options in effect:
  --bfile ./02_activities/data/gwa.qc.A1
  --extract ./02_activities/data/snplist.txt
  --hardy
  --out ./02_activities/data/gwa_qc_A1_hwe_snplist

Start time: Sat Mar 21 01:43:18 2026
7973 MiB RAM detected; reserving 3986 MiB for main workspace.
Using up to 8 compute threads.
4000 samples (2000 females, 2000 males; 4000 founders) loaded from
./02_activities/data/gwa.qc.A1.fam.
101083 variants loaded from ./02_activities/data/gwa.qc.A1.bim.
1 quantitative phenotype loaded (4000 values).
--extract: 4 variants remaining.
Calculating allele frequencies... 0%done.
--hardy: 0%25%50%75%
--hardy: Autosomal Hardy-Weinberg report (founders only) written to
./02_activities/data/gwa_qc_A1_hwe_snplist.hardy .
End time: Sat Mar 21 01:43:18 2026</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>hwesnplist <span class="ot">&lt;-</span> <span class="fu">fread</span>(<span class="st">"./02_activities/data/gwa_qc_A1_hwe_snplist.hardy"</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(hwesnplist)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   #CHROM         ID     A1     AX HOM_A1_CT HET_A1_CT TWO_AX_CT O(HET_A1)
    &lt;int&gt;     &lt;char&gt; &lt;char&gt; &lt;char&gt;     &lt;int&gt;     &lt;int&gt;     &lt;int&gt;     &lt;num&gt;
1:      1  rs3813199      G      A      3531       428        12  0.107781
2:      1 rs11804831      T      C      2820      1061        81  0.267794
3:      1  rs3128342      C      A      1927      1655       382  0.417508
4:      1     rs1861      C      A      3551       398        15  0.100404
   E(HET_A1)        P
       &lt;num&gt;    &lt;num&gt;
1:  0.107347 1.000000
2:  0.261040 0.113354
3:  0.424044 0.330273
4:  0.102143 0.274719</code></pre>
</div>
</div>
<p>The P-values for rs1861, rs3813199, rs3128342, and rs11804831 are:</p>
<p>rs1861: 0.274719, rs3813199: 1, rs3128342:0.330273, rs11804831: 0.113354</p>
</section>
<section id="question-4-genetic-association-test" class="level4">
<h4 class="anchored" data-anchor-id="question-4-genetic-association-test">Question 4: Genetic Association Test</h4>
<ol type="i">
<li>Conduct a linear regression to test the association between SNP rs1861 and the phenotype. What is the p-value?</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="bu">printf</span> <span class="st">"%s\n"</span> rs1861 <span class="op">&gt;</span> ./02_activities/data/target.txt</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="ex">plink2</span> <span class="at">--bfile</span> ./02_activities/data/gwa.qc.A1 <span class="dt">\</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">--extract</span> ./02_activities/data/target.txt <span class="dt">\</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">--recode</span> A <span class="dt">\</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">--out</span> ./02_activities/data/geno.additive.target</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>PLINK v2.0.0-a.7 64-bit (10 Jan 2026)               cog-genomics.org/plink/2.0/
(C) 2005-2026 Shaun Purcell, Christopher Chang    GNU General Public License v3
Logging to ./02_activities/data/geno.additive.target.log.
Options in effect:
  --bfile ./02_activities/data/gwa.qc.A1
  --export A
  --extract ./02_activities/data/target.txt
  --out ./02_activities/data/geno.additive.target

Start time: Sat Mar 21 01:43:18 2026
7973 MiB RAM detected; reserving 3986 MiB for main workspace.
Using up to 8 compute threads.
4000 samples (2000 females, 2000 males; 4000 founders) loaded from
./02_activities/data/gwa.qc.A1.fam.
101083 variants loaded from ./02_activities/data/gwa.qc.A1.bim.
1 quantitative phenotype loaded (4000 values).
--extract: 1 variant remaining.
1 variant remaining after main filters.

--export A pass 1/1: loading... 0%writing... 0%1%2%3%4%5%6%7%8%9%10%11%12%13%14%15%16%17%18%19%20%21%22%23%24%25%26%27%28%29%30%31%32%33%34%35%36%37%38%39%40%41%42%43%44%45%46%47%48%49%50%51%52%53%54%55%56%57%58%59%60%61%62%63%64%65%66%67%68%69%70%71%72%73%74%75%76%77%78%79%80%81%82%83%84%85%86%87%88%89%90%91%92%93%94%95%96%97%98%99% done.
--export A: ./02_activities/data/geno.additive.target.raw written.
End time: Sat Mar 21 01:43:18 2026</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>geno_subset <span class="ot">&lt;-</span> <span class="fu">fread</span>(<span class="st">"./02_activities/data/geno.additive.target.raw"</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>geno_subset<span class="ot">=</span><span class="fu">na.omit</span>(geno_subset)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(geno_subset<span class="sc">$</span>PHENOTYPE)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    -2.0067    -1.94041    -1.54387    -1.18084    -1.17827    -1.14314 
          1           1           1           1           1           1 
     -1.105    -1.05683    -1.03093     -1.0297    -1.02158    -1.00266 
          1           1           1           1           1           1 
  -0.975099   -0.974176   -0.971624   -0.932343   -0.915812   -0.856394 
          1           1           1           1           1           1 
  -0.850266   -0.850182   -0.832086   -0.830977   -0.816259   -0.815785 
          1           1           1           1           1           1 
   -0.81405   -0.813697   -0.789221   -0.784591   -0.776985   -0.764797 
          1           1           1           1           1           1 
  -0.741179   -0.733156    -0.70895   -0.706932    -0.69353   -0.692611 
          1           1           1           1           1           1 
  -0.689723    -0.68926   -0.675043   -0.674414   -0.667257   -0.618352 
          1           1           1           1           1           1 
  -0.609025   -0.601817   -0.587255    -0.57976    -0.57673    -0.57218 
          1           1           1           1           1           1 
  -0.562768   -0.559819    -0.52704   -0.524089   -0.522741    -0.48713 
          1           1           1           1           1           1 
  -0.472131   -0.468311   -0.463205   -0.454594   -0.445879   -0.440292 
          1           1           1           1           1           1 
  -0.430607   -0.425083   -0.413898   -0.411892   -0.399968   -0.383448 
          1           1           1           1           1           1 
  -0.357669   -0.353315   -0.350442   -0.348188    -0.34364   -0.328476 
          1           1           1           1           1           1 
   -0.31794   -0.305768   -0.303563   -0.300904   -0.297472   -0.281114 
          1           1           1           1           1           1 
  -0.274562   -0.274288   -0.272699   -0.272306   -0.266602   -0.263205 
          1           1           1           1           1           1 
  -0.258187   -0.255467   -0.247936   -0.246711   -0.245651   -0.243375 
          1           1           1           1           1           1 
  -0.230108   -0.229437   -0.227474   -0.218334   -0.218195   -0.216238 
          1           1           1           1           1           1 
  -0.210819   -0.207239   -0.200325   -0.190149   -0.188594    -0.18483 
          1           1           1           1           1           1 
  -0.179195   -0.176989   -0.176171   -0.171641   -0.169012    -0.16636 
          1           1           1           1           1           1 
  -0.162522   -0.149469   -0.145579    -0.14541   -0.139026   -0.133099 
          1           1           1           1           1           1 
  -0.132887   -0.128438   -0.127233   -0.125728   -0.125725   -0.123851 
          1           1           1           1           1           1 
  -0.123477   -0.111979   -0.110971   -0.108387    -0.10092  -0.0925348 
          1           1           1           1           1           1 
 -0.0907701  -0.0768656  -0.0748324  -0.0733488   -0.071508  -0.0662198 
          1           1           1           1           1           1 
 -0.0630322  -0.0588159  -0.0585135   -0.056892  -0.0568889  -0.0483632 
          1           1           1           1           1           1 
 -0.0395887  -0.0374686  -0.0361995  -0.0328347  -0.0300544  -0.0297092 
          1           1           1           1           1           1 
 -0.0274569  -0.0269739  -0.0227255  -0.0198447   -0.018232  -0.0176171 
          1           1           1           1           1           1 
 -0.0160016  -0.0143666  -0.0103116 -0.00911379 -0.00768049 -0.00487259 
          1           1           1           1           1           1 
-0.00294084 -0.00213904  0.00922808  0.00943468   0.0100865   0.0163016 
          1           1           1           1           1           1 
  0.0168877   0.0192963   0.0218095   0.0237329   0.0242567   0.0332797 
          1           1           1           1           1           1 
  0.0347547    0.037212    0.040534   0.0413755   0.0439456   0.0483661 
          1           1           1           1           1           1 
  0.0493582   0.0502875   0.0569924   0.0719959   0.0724566   0.0740857 
          1           1           1           1           1           1 
  0.0794715   0.0897564   0.0989155   0.0997447    0.102955    0.103211 
          1           1           1           1           1           1 
   0.103274    0.108107    0.110363    0.112657     0.12883    0.130603 
          1           1           1           1           1           1 
   0.143846    0.148892      0.1529    0.154673    0.155205    0.156625 
          1           1           1           1           1           1 
   0.157966    0.158754    0.159938    0.160158    0.161206     0.16615 
          1           1           1           1           1           1 
   0.166423    0.169362    0.169693    0.172238    0.174426    0.176619 
          1           1           1           1           1           1 
   0.181355    0.184127    0.186792    0.188037    0.191453    0.192407 
          1           1           1           1           1           1 
   0.194063    0.196173     0.19699    0.197191    0.198172    0.199205 
          1           1           1           1           1           1 
   0.203321    0.208239    0.210465    0.215159    0.216337    0.222758 
          1           1           1           1           1           1 
   0.224171    0.229195    0.230119    0.235194    0.236254    0.241169 
          1           1           1           1           1           1 
   0.242851      0.2433    0.244522    0.246076    0.247448    0.251244 
          1           1           1           1           1           1 
   0.253064    0.253631    0.260749    0.261033    0.261234    0.261381 
          1           1           1           1           1           1 
   0.261391    0.261495    0.262738    0.262836    0.266835     0.26851 
          1           1           1           1           1           1 
   0.272287    0.274274    0.276109    0.277181    0.280151    0.282595 
          1           1           1           1           1           1 
   0.282601    0.283516    0.285965    0.286781    0.287955    0.289644 
          1           1           1           1           1           1 
   0.289995    0.290045    0.294585    0.297262    0.300136    0.300889 
          1           1           1           1           1           1 
   0.300977    0.302799    0.304831    0.308177    0.308268    0.308898 
          1           1           1           1           1           1 
    0.31336    0.323827    0.328217    0.329167    0.334411    0.335608 
          1           1           1           1           1           1 
   0.338495    0.342723     0.34727    0.349449    0.349523    0.350116 
          1           1           1           1           1           1 
   0.359176    0.359769    0.360193    0.363739    0.370105    0.370582 
          1           1           1           1           1           1 
   0.371147     0.37202    0.374083    0.378038    0.378221    0.383345 
          1           1           1           1           1           1 
   0.385721    0.390212    0.392111    0.392774    0.393118    0.393302 
          1           1           1           1           1           1 
   0.393804    0.394035    0.396461    0.397647    0.401571    0.406481 
          1           1           1           1           1           1 
    0.40852     0.41024    0.412346    0.412432    0.413153    0.413936 
          1           1           1           1           1           1 
   0.414247    0.415853     0.42091    0.423619    0.425966    0.428812 
          1           1           1           1           1           1 
   0.429489    0.430329    0.431138    0.431761    0.438649    0.440058 
          1           1           1           1           1           1 
   0.441162    0.443122    0.445529     0.44713    0.448201    0.451096 
          1           1           1           1           1           1 
   0.452488    0.457658    0.459392     0.45966    0.459898    0.460508 
          1           1           1           1           1           1 
   0.460707     0.46164    0.464111    0.465746    0.467102    0.469739 
          1           1           1           1           1           1 
   0.470054    0.473671    0.475119    0.476606    0.477996    0.478461 
          1           1           1           1           1           1 
   0.479397    0.480266    0.481141    0.481596    0.481736     0.48253 
          1           1           1           1           1           1 
   0.484471    0.489508    0.490777    0.491566    0.492441    0.493607 
          1           1           1           1           1           1 
   0.494219    0.498679    0.498998    0.500145    0.500521    0.503298 
          1           1           1           1           1           1 
   0.504558       0.506    0.506915    0.506992    0.510362     0.51068 
          1           1           1           1           1           1 
   0.513128    0.513393    0.515092    0.518396    0.518936    0.523523 
          1           1           1           1           1           1 
   0.530904     0.53154    0.533472    0.535054    0.535111     0.53747 
          1           1           1           1           1           1 
   0.537931      0.5387    0.539352     0.54114    0.542146    0.542232 
          1           1           1           1           1           1 
   0.543258    0.545867    0.551188    0.553896    0.555431     0.55592 
          1           1           1           1           1           1 
   0.556374    0.560423    0.560938    0.561201    0.561957    0.562266 
          1           1           1           1           1           1 
   0.564904    0.567218    0.567652    0.568484    0.570998    0.571552 
          1           1           1           1           1           1 
   0.572653    0.577296    0.578509    0.579788    0.580932    0.583804 
          1           1           1           1           1           1 
   0.584283    0.588147    0.588787    0.590307    0.592705    0.593908 
          1           1           1           1           1           1 
   0.596424    0.596486    0.597771    0.597881     0.59978    0.603409 
          1           1           1           1           1           1 
   0.606901    0.609945    0.614105     0.61483    0.615232    0.615501 
          1           1           1           1           1           1 
   0.615796    0.615945    0.616137    0.622022    0.622953    0.623251 
          1           1           1           1           1           1 
    0.62447    0.624681    0.625014    0.625496    0.625631    0.627771 
          1           1           1           1           1           1 
   0.629241    0.631444    0.632784    0.634215    0.634281    0.636635 
          1           1           1           1           1           1 
   0.637476    0.637992    0.638173    0.639023    0.643502    0.645526 
          1           1           1           1           1           1 
   0.646017    0.646175    0.647063    0.647676    0.648158    0.648768 
          1           1           1           1           1           1 
   0.652472    0.652524    0.652813    0.653122     0.65421    0.654743 
          1           1           1           1           1           1 
   0.654969    0.655982    0.656508    0.658884    0.659021    0.659254 
          1           1           1           1           1           1 
   0.659526     0.66096    0.661183     0.66187    0.663798    0.666573 
          1           1           1           1           1           1 
   0.667063     0.66866     0.67086    0.671108    0.671119    0.671177 
          1           1           1           1           1           1 
    0.67187     0.67311    0.673946    0.674836    0.676559    0.676643 
          1           1           1           1           1           1 
   0.678072    0.678644     0.67871    0.679204    0.681635    0.684695 
          1           1           1           1           1           1 
   0.685218    0.685656    0.687805    0.688531    0.689944    0.692137 
          1           1           1           1           1           1 
   0.696145    0.696585    0.696591    0.697774    0.701086    0.701096 
          1           1           1           1           1           1 
   0.705762    0.706874    0.707476    0.707994    0.708295     0.70969 
          1           1           1           1           1           1 
   0.716415    0.718686    0.722509    0.722858    0.723325    0.724833 
          1           1           1           1           1           1 
   0.729386    0.732269    0.733231    0.734205    0.734507      0.7354 
          1           1           1           1           1           1 
   0.736739    0.737313    0.737751    0.740429    0.742208    0.744277 
          1           1           1           1           1           1 
   0.746004    0.751006      0.7524    0.752486    0.753162    0.755484 
          1           1           1           1           1           1 
   0.757071    0.759024    0.759204    0.759766    0.760466    0.762756 
          1           1           1           1           1           1 
   0.763652    0.765235    0.765761    0.767662    0.767909    0.768185 
          1           1           1           1           1           1 
   0.768646     0.76887    0.769012    0.769415    0.770047    0.771752 
          1           1           1           1           1           1 
   0.772601    0.772602    0.773395    0.773937    0.776357     0.77954 
          1           1           1           1           1           1 
    0.78021    0.780345    0.781729     0.78175    0.785047    0.786749 
          1           1           1           1           1           1 
   0.789129    0.789408    0.789445    0.791564    0.793061    0.796137 
          1           1           1           1           1           1 
   0.796591    0.796703    0.801004     0.80505    0.806523    0.808443 
          1           1           1           1           1           1 
   0.810028    0.811969    0.812837    0.813813    0.814215    0.815626 
          1           1           1           1           1           1 
    0.81636    0.817854    0.818055    0.818711    0.818848    0.820499 
          1           1           1           1           1           1 
   0.821299    0.823262    0.825096    0.825726    0.825874    0.827241 
          1           1           1           1           1           1 
   0.828144    0.828628    0.828728    0.829168     0.82956    0.829605 
          1           1           1           1           1           1 
   0.831058     0.83317    0.833315    0.833353    0.835118    0.836982 
          1           1           1           1           1           1 
    0.83715    0.839409    0.840821    0.840852     0.84089    0.842492 
          1           1           1           1           1           1 
   0.845106    0.845176    0.846762    0.847563    0.848357    0.849144 
          1           1           1           1           1           1 
   0.850521    0.851854    0.851978    0.853135    0.854815    0.855136 
          1           1           1           1           1           1 
    0.85678    0.858758    0.860254    0.861026    0.861941    0.864579 
          1           1           1           1           1           1 
    0.86921    0.869393    0.870997    0.871825    0.874552    0.876795 
          1           1           1           1           1           1 
   0.878781    0.879089    0.879486    0.880526    0.883153    0.883472 
          1           1           1           1           1           1 
   0.883732    0.888041    0.890834    0.891428    0.891435    0.891998 
          1           1           1           1           1           1 
   0.892317    0.894118    0.895266    0.895541     0.89829    0.898871 
          1           1           1           1           1           1 
   0.899866    0.899892     0.90127    0.901478    0.902415    0.903429 
          1           1           1           1           1           1 
   0.905888    0.906219    0.906528    0.907576    0.914361     0.91494 
          1           1           1           1           1           1 
   0.917241    0.917278    0.917862    0.918062    0.918224    0.918496 
          1           1           1           1           1           1 
   0.919543    0.919754    0.921349    0.924187    0.924297    0.926438 
          1           1           1           1           1           1 
   0.926552    0.927125    0.927676    0.930023    0.930537    0.931317 
          1           1           1           1           1           1 
   0.932008    0.936678    0.937765    0.940246    0.940673    0.941966 
          1           1           1           1           1           1 
   0.942216    0.942742     0.94474    0.945212     0.94533    0.945343 
          1           1           1           1           1           1 
   0.945384    0.947081    0.947884    0.948099    0.948616    0.949683 
          1           1           1           1           1           1 
    0.95025    0.950874    0.952067    0.952336    0.953787    0.954538 
          1           1           1           1           1           1 
   0.956253    0.957155    0.959114    0.959196    0.960324    0.960372 
          1           1           1           1           1           1 
   0.961682    0.961878    0.963747    0.964232     0.96826    0.968292 
          1           1           1           1           1           1 
   0.969302    0.970271    0.970901    0.971196    0.971204      0.9717 
          1           1           1           1           1           1 
   0.971839    0.972233     0.97264    0.972865    0.973019    0.973228 
          1           1           1           1           1           1 
   0.974161    0.976472    0.976883    0.977361     0.97761    0.978503 
          1           1           1           1           1           1 
    0.97877    0.979299    0.982041    0.984441    0.985453     0.98577 
          1           1           1           1           1           1 
   0.985879     0.98613      0.9885    0.989348    0.994527    0.996319 
          1           1           1           1           1           1 
   0.996956    0.998304     0.99975     1.00159     1.00187     1.00223 
          1           1           1           1           1           1 
    1.00297     1.00311     1.00463     1.00601     1.00779     1.00827 
          1           1           1           1           1           1 
    1.00854     1.01001     1.01185     1.01251     1.01253     1.01348 
          1           1           1           1           1           1 
    1.01541     1.01576     1.01602      1.0164     1.01696     1.01807 
          1           1           1           1           1           1 
     1.0184     1.01884     1.01885     1.01951     1.01954     1.02039 
          1           1           1           1           1           1 
    1.02141     1.02336     1.02386     1.02388     1.02498     1.02542 
          1           1           1           1           1           1 
    1.02606     1.02635     1.02636     1.02938     1.03241     1.03303 
          1           1           1           1           1           1 
    1.03413     1.03555      1.0357     1.03673     1.03802     1.03854 
          1           1           1           1           1           1 
    1.03868     1.04005     1.04039     1.04106     1.04204     1.04435 
          1           1           1           1           1           1 
    1.04451     1.04552     1.04646     1.04677     1.04699      1.0482 
          1           1           1           1           1           1 
    1.04862      1.0489     1.04899      1.0511     1.05123     1.05284 
          1           1           1           1           1           1 
    1.05327     1.05343     1.05371     1.05468     1.05508     1.05625 
          1           1           1           1           1           1 
    1.05628     1.05643      1.0571     1.05715     1.05718     1.05723 
          1           1           1           1           1           1 
    1.05752     1.05934     1.06033     1.06036      1.0611     1.06284 
          1           1           1           1           1           1 
    1.06405      1.0649     1.06499     1.06681     1.06764     1.06862 
          1           1           1           1           1           1 
    1.06867     1.07138     1.07147     1.07196     1.07287     1.07365 
          1           1           1           1           1           1 
    1.07434      1.0756     1.07562      1.0767     1.07726     1.07727 
          1           1           1           1           1           1 
    1.07759       1.078     1.07858     1.07868     1.08217     1.08222 
          1           1           1           1           1           1 
    1.08281     1.08353     1.08368     1.08531     1.08532     1.08633 
          1           1           1           1           1           1 
    1.08668      1.0872     1.08888     1.08895     1.09089      1.0914 
          1           1           1           1           1           1 
    1.09174      1.0921     1.09252     1.09256     1.09649     1.09779 
          1           1           1           1           1           2 
    1.09811     1.09864      1.0987     1.09879     1.09901     1.09954 
          1           1           1           1           1           1 
    1.10019     1.10244     1.10285     1.10299     1.10334     1.10395 
          1           1           1           1           1           1 
    1.10433     1.10542     1.10654     1.10661     1.10858     1.10892 
          1           1           1           1           1           1 
    1.10906     1.11021      1.1119     1.11288     1.11301     1.11336 
          1           1           1           1           1           1 
    1.11367     1.11485     1.11717     1.11732     1.11909      1.1212 
          1           1           1           1           1           1 
    1.12162     1.12273     1.12368     1.12528     1.12574     1.12622 
          1           1           1           1           1           1 
    1.12655     1.12782     1.12904     1.12979     1.13011     1.13322 
          1           1           1           1           1           1 
    1.13341     1.13473     1.13549     1.13692     1.13693      1.1372 
          1           1           1           1           1           1 
    1.13987     1.14009      1.1411     1.14298      1.1432      1.1445 
          1           1           1           1           1           1 
    1.14452     1.14455     1.14497     1.14641     1.14796     1.14817 
          1           1           1           1           1           1 
    1.14821     1.14926     1.14927     1.14963     1.15074     1.15087 
          1           1           1           1           1           1 
    1.15172     1.15274     1.15323     1.15325     1.15398     1.15658 
          1           1           1           1           1           1 
    1.15773     1.15862      1.1588      1.1589     1.15981     1.16468 
          1           1           1           1           1           1 
    1.16516     1.16597     1.16645     1.16757     1.16769     1.16781 
          1           1           1           1           1           1 
    1.16897     1.16948     1.16995     1.17067     1.17189     1.17378 
          1           1           1           1           1           1 
     1.1739     1.17427     1.17556      1.1758     1.17693     1.17842 
          1           1           1           1           1           1 
    1.18177     1.18186     1.18244     1.18262     1.18267     1.18298 
          1           1           1           1           1           1 
    1.18315     1.18444     1.18526     1.18574     1.18643     1.18646 
          1           1           1           1           1           1 
    1.18755     1.18866     1.18989     1.19277     1.19367     1.19402 
          1           1           1           1           1           1 
    1.19464     1.19759     1.19987     1.20116     1.20344     1.20387 
          1           1           1           1           1           2 
    1.20421     1.20455      1.2065      1.2068      1.2081     1.20956 
          1           1           1           1           1           1 
    1.21051     1.21105     1.21244     1.21318     1.21343      1.2138 
          1           1           1           1           1           1 
    1.21403     1.21478     1.21507     1.21626     1.21733     1.21793 
          1           1           1           1           1           1 
      1.218     1.21811     1.21845      1.2206     1.22087     1.22204 
          1           1           1           1           1           1 
    1.22286     1.22313     1.22336     1.22362     1.22514     1.22666 
          1           1           1           1           1           1 
    1.22807      1.2283     1.22844     1.22865      1.2292     1.23003 
          1           1           1           1           1           1 
    1.23044     1.23416     1.23555      1.2364     1.23645      1.2374 
          1           1           1           1           1           1 
    1.23789     1.23838     1.23844     1.23866     1.23905     1.23953 
          1           1           1           1           1           1 
    1.24054     1.24073     1.24475     1.24566     1.24573     1.24648 
          1           1           1           1           1           1 
     1.2469      1.2473     1.24801     1.24817     1.24831     1.24947 
          1           1           1           1           1           1 
    1.25027     1.25071     1.25156     1.25169     1.25244     1.25253 
          1           1           1           1           1           1 
    1.25291     1.25503     1.25529     1.25556     1.25617      1.2578 
          1           1           1           1           1           1 
    1.25843     1.25928     1.26119     1.26159     1.26254     1.26279 
          1           1           1           1           1           1 
     1.2637     1.26391     1.26431     1.26491     1.26523     1.26534 
          1           1           1           1           1           1 
     1.2661     1.26814     1.26871     1.27009     1.27294     1.27536 
          1           1           1           1           1           1 
    1.27568     1.27596     1.27641     1.27708     1.27785     1.27873 
          1           1           1           1           1           1 
    1.27907     1.27917     1.27957     1.28054     1.28069     1.28099 
          1           2           1           1           1           1 
    1.28163     1.28199     1.28327      1.2835     1.28546     1.28592 
          1           1           1           1           1           1 
    1.28678     1.28709     1.28781      1.2883     1.28844     1.28953 
          1           1           1           1           1           1 
    1.29121     1.29157     1.29163     1.29261     1.29275      1.2934 
          1           1           1           1           1           1 
    1.29536     1.29577     1.29586     1.29684     1.29762     1.29937 
          1           1           1           1           1           1 
     1.3003     1.30172     1.30235     1.30269     1.30453     1.30459 
          1           1           1           1           1           1 
    1.30529     1.30538     1.30581     1.31008      1.3104     1.31079 
          1           1           1           1           1           1 
    1.31228     1.31293      1.3133     1.31494       1.315     1.31544 
          1           1           1           1           1           1 
    1.31693     1.31704     1.31788     1.31869     1.31924     1.31998 
          1           1           1           1           1           1 
    1.32039     1.32067     1.32094     1.32099     1.32179     1.32209 
          1           1           1           1           1           1 
    1.32304     1.32314     1.32318     1.32424     1.32434     1.32473 
          1           1           1           1           1           1 
    1.32474     1.32518     1.32576     1.32615     1.32752     1.32794 
          1           1           1           1           1           1 
    1.32836     1.33242     1.33326     1.33345     1.33352     1.33387 
          1           1           1           1           1           1 
    1.33524      1.3367     1.33793     1.33812     1.33849     1.34006 
          1           1           1           1           1           1 
    1.34057     1.34074     1.34114      1.3413     1.34208     1.34315 
          1           1           1           1           1           1 
     1.3442     1.34421     1.34425     1.34443     1.34532     1.34541 
          1           1           1           1           1           1 
    1.34585     1.34601     1.34626     1.34641     1.34666     1.34685 
          1           1           1           1           1           1 
    1.34847     1.34869     1.35045     1.35055     1.35098     1.35227 
          1           1           1           1           1           1 
    1.35336     1.35353     1.35396     1.35524     1.35538      1.3555 
          1           1           1           1           1           1 
    1.35583     1.35587     1.35698     1.35782     1.35831      1.3588 
          1           1           1           1           1           1 
    1.35905     1.36095      1.3637     1.36472     1.36506     1.36514 
          1           1           1           2           1           1 
    1.36549      1.3655     1.36613     1.36669     1.36729     1.36786 
          1           1           1           1           1           1 
    1.36902     1.36908     1.37084     1.37133     1.37162      1.3731 
          1           1           1           1           1           1 
    1.37414     1.37554     1.37771     1.37983     1.38062     1.38072 
          1           1           1           1           1           1 
    1.38123     1.38198     1.38228     1.38348     1.38475      1.3855 
          1           1           1           1           1           1 
    1.38744     1.38774     1.39007     1.39061      1.3907     1.39182 
          1           1           1           1           1           1 
    1.39231     1.39326     1.39369     1.39383     1.39549     1.39765 
          1           1           1           1           1           1 
    1.39786     1.39985     1.40041     1.40206     1.40237     1.40469 
          1           1           1           1           1           1 
    1.40489     1.40575     1.40636     1.40638     1.40793     1.40844 
          1           1           1           1           1           1 
    1.40902     1.40921     1.41079     1.41214     1.41265     1.41343 
          1           1           1           1           1           1 
    1.41633     1.41856     1.41877     1.41889      1.4189     1.41991 
          1           1           1           1           1           1 
    1.42043     1.42058     1.42243     1.42301     1.42311     1.42361 
          1           1           1           1           1           1 
     1.4238     1.42407     1.42482     1.42522     1.42556     1.42577 
          1           1           1           1           1           1 
    1.42782     1.42988     1.43097     1.43197     1.43251     1.43252 
          1           1           1           1           1           1 
    1.43256      1.4328     1.43371      1.4338     1.43442     1.43452 
          1           1           1           1           1           1 
    1.43532     1.43584     1.43652     1.43805     1.43818     1.43889 
          1           1           1           1           1           1 
    1.43947     1.44134     1.44307      1.4439     1.44709     1.44764 
          1           1           1           1           1           1 
    1.44792     1.45194      1.4524     1.45242     1.45364     1.45397 
          1           1           1           1           1           1 
    1.45456     1.45546     1.45637     1.45687     1.45846     1.45899 
          1           1           1           1           1           1 
    1.45983     1.46035      1.4604     1.46219     1.46241     1.46279 
          2           1           1           1           1           1 
    1.46451     1.46497       1.465     1.46531     1.46541     1.46553 
          1           1           1           1           1           1 
    1.46616     1.46637     1.46773     1.46818     1.46886     1.46913 
          1           1           1           1           1           1 
    1.46933     1.46985     1.47203     1.47224     1.47516     1.47538 
          1           1           1           1           1           1 
    1.47617     1.47714     1.47808     1.47927     1.47941     1.47957 
          1           1           1           1           1           1 
    1.47966     1.47975     1.47984     1.48161     1.48366      1.4837 
          1           1           1           1           1           1 
    1.48394      1.4845     1.48501     1.48524     1.48559     1.48563 
          1           1           1           1           1           1 
     1.4878     1.48819     1.48866     1.48965     1.49044     1.49131 
          1           1           1           1           1           1 
    1.49178     1.49201     1.49248     1.49384     1.49479     1.49544 
          1           1           1           1           1           1 
    1.49555     1.49639     1.49679      1.4971     1.49734     1.49864 
          1           1           1           1           1           1 
     1.4993     1.49942     1.49973     1.50071     1.50175      1.5036 
          1           1           1           1           1           1 
      1.506      1.5076     1.50847     1.50876     1.50879     1.50893 
          1           1           1           1           1           1 
    1.50908     1.50936     1.50937     1.50941     1.51073     1.51126 
          1           1           1           1           1           1 
    1.51129     1.51204     1.51257      1.5143     1.51461     1.51523 
          1           1           1           1           1           1 
    1.51582      1.5188     1.51933     1.51936     1.51998     1.52027 
          1           1           1           1           1           1 
    1.52326      1.5234     1.52372     1.52503      1.5252     1.52583 
          1           1           1           1           1           1 
    1.52724     1.52756     1.52887     1.52895      1.5303     1.53035 
          1           1           1           1           1           1 
    1.53069     1.53118     1.53167     1.53193     1.53248     1.53262 
          1           1           1           1           1           1 
    1.53385     1.53608     1.53611     1.53624     1.53675     1.53811 
          1           1           1           1           1           1 
     1.5392     1.53959     1.54022     1.54026     1.54038     1.54066 
          1           1           1           1           1           1 
    1.54111     1.54233     1.54308     1.54342     1.54362     1.54561 
          1           1           1           1           1           1 
    1.54576      1.5461     1.54649     1.54725     1.54891     1.54917 
          1           1           1           1           1           1 
    1.54963     1.55063     1.55289     1.55568     1.55732     1.55755 
          1           1           1           1           1           1 
    1.55823     1.55902     1.56022     1.56107     1.56278     1.56309 
          1           1           1           1           1           1 
    1.56313     1.56402     1.56429     1.56437     1.56474     1.56486 
          1           1           1           1           1           1 
    1.56526     1.56613     1.56615     1.56622     1.56778     1.56806 
          1           1           1           1           1           1 
    1.56842     1.56868     1.57181     1.57216     1.57226     1.57248 
          1           1           1           1           1           1 
    1.57254     1.57319     1.57373     1.57381     1.57457     1.57472 
          1           1           1           1           1           1 
    1.57515     1.57657     1.57744     1.57886      1.5806     1.58118 
          1           1           1           1           1           1 
    1.58165     1.58333     1.58354     1.58385      1.5851     1.58598 
          1           1           1           1           1           1 
    1.58647     1.58827     1.58881     1.58896     1.58935     1.58973 
          1           1           1           1           1           1 
    1.59003     1.59094     1.59309     1.59358     1.59497     1.59817 
          1           1           1           1           1           1 
    1.59887     1.59891     1.59898     1.60135     1.60229     1.60232 
          1           1           1           1           1           1 
    1.60269     1.60431     1.60439     1.60509     1.60525     1.60529 
          1           1           1           1           1           1 
    1.60583      1.6077     1.60948     1.60976     1.60977     1.61031 
          1           1           1           1           1           1 
     1.6104     1.61303     1.61454      1.6148     1.61656     1.61736 
          1           1           1           1           1           1 
    1.61933     1.62007     1.62021      1.6207     1.62082     1.62224 
          1           1           1           1           1           1 
    1.62253     1.62296     1.62414     1.62461     1.62525     1.62614 
          1           1           1           1           1           1 
    1.62873     1.63007     1.63079     1.63134     1.63315     1.63327 
          1           1           1           1           1           1 
    1.63359     1.63453     1.63534      1.6362     1.64078      1.6408 
          1           1           1           1           1           1 
    1.64177     1.64209      1.6428     1.64301     1.64378     1.64502 
          1           1           1           1           1           1 
    1.64515     1.64559     1.64577     1.64688     1.64779      1.6493 
          1           1           1           1           1           1 
       1.65       1.651     1.65177     1.65241     1.65267     1.65289 
          1           1           1           1           1           1 
    1.65331     1.65352     1.65359     1.65395     1.65428     1.65461 
          1           1           1           1           1           1 
    1.65538     1.65639     1.65644     1.65651     1.65719     1.65741 
          1           1           1           1           1           1 
    1.65831     1.65883     1.65961     1.65973     1.66152     1.66353 
          1           1           1           1           1           1 
    1.66462     1.66488     1.66528      1.6661     1.66626     1.66654 
          1           1           1           1           1           1 
    1.66719     1.66771     1.66786     1.66808     1.66889     1.66985 
          1           1           1           1           1           1 
    1.67148     1.67177      1.6724     1.67341     1.67413     1.67511 
          1           1           1           1           1           1 
    1.67661     1.67729     1.67733     1.67916     1.67984     1.68072 
          1           1           1           1           1           1 
      1.681     1.68224     1.68252      1.6833     1.68352     1.68394 
          1           1           1           1           1           1 
    1.68451     1.68536     1.68563     1.68577     1.68639     1.68752 
          1           1           1           1           1           1 
    1.68762     1.68792     1.68966     1.69118     1.69144     1.69205 
          1           1           1           1           1           1 
    1.69222     1.69309     1.69434     1.69463     1.69503      1.6957 
          1           1           1           1           1           1 
    1.69572     1.69594     1.69615     1.69627     1.69697     1.69722 
          1           1           1           1           1           1 
     1.6984     1.69847     1.69893     1.69996     1.70025      1.7007 
          1           1           1           1           1           1 
    1.70094      1.7013     1.70148     1.70392     1.70583     1.70598 
          1           1           1           1           1           1 
    1.70682     1.70819     1.70874     1.71031     1.71137     1.71152 
          1           1           1           1           1           1 
    1.71204     1.71236     1.71347     1.71453     1.71464     1.71492 
          1           1           1           1           1           1 
    1.71657     1.71702     1.71749     1.71752     1.71839     1.71883 
          1           1           1           1           1           1 
    1.71906     1.71941     1.71948     1.71953     1.72044     1.72213 
          1           1           1           1           1           1 
    1.72217      1.7223     1.72269     1.72346     1.72368     1.72372 
          1           1           1           1           1           1 
    1.72424     1.72459     1.72461     1.72487     1.72521     1.72682 
          1           1           1           2           1           1 
    1.72741     1.72793     1.72892     1.72952        1.73      1.7302 
          1           1           1           1           1           1 
    1.73021      1.7306     1.73151     1.73154     1.73175     1.73271 
          1           1           1           1           1           1 
    1.73309     1.73311     1.73341     1.73381     1.73446     1.73447 
          1           1           1           1           1           1 
    1.73692     1.73704     1.73937     1.74003     1.74005     1.74024 
          1           1           1           1           1           1 
    1.74267     1.74301     1.74328     1.74659     1.74719     1.74845 
          1           1           1           1           1           1 
    1.74871     1.75184     1.75365     1.75378      1.7539      1.7544 
          1           1           1           1           1           2 
    1.75504     1.75703     1.75747     1.75749     1.75814     1.75973 
          1           1           1           1           1           1 
    1.76042     1.76109      1.7611     1.76124      1.7629     1.76468 
          1           1           1           1           1           1 
    1.76598     1.76852     1.76973     1.77041      1.7717     1.77199 
          1           1           1           2           1           1 
    1.77283       1.774     1.77448     1.77461     1.77586     1.77601 
          1           1           1           1           1           1 
    1.77608      1.7761     1.77762     1.77766     1.77815     1.77973 
          1           1           1           1           1           1 
    1.78012     1.78042     1.78059     1.78062      1.7807     1.78212 
          1           1           1           1           1           1 
    1.78309     1.78337     1.78469     1.78525     1.78576     1.78578 
          1           1           1           1           1           1 
     1.7858     1.78597      1.7861     1.78648     1.78684     1.78729 
          1           1           1           1           1           1 
    1.78737     1.78862     1.79021     1.79025     1.79207     1.79324 
          1           1           1           1           1           1 
    1.79335     1.79344     1.79515      1.7953     1.79586     1.79618 
          1           1           1           1           1           1 
    1.79689      1.7971     1.79714     1.79977     1.80017     1.80089 
          1           1           1           1           1           1 
     1.8017     1.80172     1.80177     1.80318     1.80337     1.80427 
          1           1           1           1           1           2 
    1.80473     1.80493     1.80526     1.80692     1.80721     1.80747 
          1           1           1           1           1           1 
     1.8075     1.80776     1.80952     1.80955      1.8097     1.80981 
          1           1           1           1           1           1 
    1.80986     1.81075     1.81194     1.81204     1.81222      1.8123 
          1           1           1           1           1           1 
    1.81643     1.81666     1.81683     1.81695     1.81763     1.81998 
          1           1           1           1           1           1 
    1.82117     1.82219     1.82231     1.82263     1.82301     1.82373 
          1           1           1           1           1           1 
     1.8241     1.82457      1.8248     1.82576     1.82585     1.82728 
          1           1           1           1           1           1 
    1.82811     1.82923     1.82931     1.83079     1.83161     1.83186 
          1           1           1           1           1           1 
    1.83246     1.83312     1.83364     1.83526      1.8356     1.83588 
          1           1           1           1           1           1 
     1.8361     1.83778     1.83807      1.8385     1.83948     1.83982 
          1           1           1           1           1           1 
    1.83988     1.84101     1.84109     1.84232     1.84287     1.84406 
          1           1           1           1           1           1 
    1.84443     1.84463     1.84745     1.84752     1.84788     1.84938 
          1           1           1           1           1           1 
    1.84947     1.85014      1.8504     1.85045     1.85123     1.85224 
          1           1           1           1           1           1 
    1.85291     1.85385     1.85417     1.85437     1.85438     1.85456 
          1           1           1           1           1           1 
    1.85459     1.85486     1.85553     1.85696     1.85702     1.85799 
          1           1           1           1           1           1 
    1.85944     1.86029     1.86078     1.86215     1.86291     1.86339 
          1           1           1           1           1           1 
    1.86369     1.86549     1.86603     1.86647      1.8667     1.86712 
          1           1           1           1           1           1 
    1.87028     1.87037     1.87126     1.87143     1.87265     1.87297 
          1           1           1           1           1           1 
    1.87361      1.8739     1.87455     1.87513     1.87616     1.87644 
          1           1           1           1           1           1 
    1.87692     1.87703     1.87809     1.87813     1.87818     1.87867 
          1           1           1           1           1           1 
     1.8788     1.87887     1.88048     1.88108     1.88119       1.882 
          1           1           1           1           1           1 
    1.88241     1.88268     1.88301     1.88302     1.88348     1.88432 
          1           1           1           1           1           1 
    1.88471     1.88584     1.88585      1.8884     1.88854     1.89096 
          1           1           1           1           1           1 
    1.89147     1.89156     1.89189     1.89225     1.89271     1.89294 
          1           1           1           1           1           1 
      1.893     1.89322     1.89326     1.89327     1.89483     1.89518 
          1           1           1           1           1           1 
    1.89543     1.89612     1.89709     1.89863     1.89864     1.89865 
          1           1           1           1           1           1 
    1.89874     1.89887     1.90078      1.9013      1.9026     1.90347 
          1           1           1           1           1           1 
    1.90384     1.90463     1.90526     1.90539     1.90542     1.90613 
          1           1           1           1           1           1 
    1.90731     1.90889     1.90997      1.9104     1.91264     1.91394 
          2           1           1           1           1           1 
    1.91501     1.91585     1.91697      1.9193     1.92065     1.92068 
          1           1           1           1           1           1 
    1.92083     1.92282     1.92284     1.92348     1.92394     1.92481 
          1           1           1           1           1           1 
    1.92502     1.92518     1.92552     1.92557     1.92663     1.92719 
          1           1           1           1           1           1 
    1.92728     1.92879     1.92976     1.92977     1.93034     1.93105 
          1           1           1           1           1           1 
    1.93146     1.93154     1.93251     1.93288     1.93359     1.93378 
          1           1           2           1           1           1 
    1.93406     1.93454     1.93596     1.93606     1.93737     1.93763 
          1           1           1           1           1           1 
    1.93805     1.93843     1.93886     1.93937     1.93999     1.94093 
          1           1           1           1           1           1 
    1.94192     1.94209     1.94263     1.94363     1.94381      1.9439 
          1           1           1           1           1           1 
    1.94436     1.94458     1.94564     1.94695     1.94743     1.94821 
          1           1           1           1           1           1 
    1.95023     1.95028     1.95066     1.95193     1.95225     1.95285 
          1           1           1           1           1           1 
    1.95293     1.95311     1.95455     1.95523     1.95644     1.95703 
          1           1           1           1           1           1 
    1.95728     1.95823     1.95979     1.96002     1.96151      1.9617 
          1           1           1           1           1           1 
    1.96219      1.9638     1.96424     1.96506     1.96607     1.96662 
          1           1           1           1           1           1 
    1.96691     1.96869     1.97052     1.97055     1.97084     1.97117 
          1           1           1           1           1           1 
    1.97176      1.9746     1.97505     1.97537     1.97549     1.97594 
          1           1           1           1           1           1 
     1.9765     1.97656     1.97745     1.97765     1.97901     1.98075 
          1           1           1           1           1           1 
    1.98233      1.9826     1.98297     1.98348     1.98416     1.98428 
          1           1           1           1           1           1 
    1.98441     1.98551     1.98585     1.98605     1.98822     1.98903 
          1           1           1           1           1           1 
     1.9898     1.99322     1.99427     1.99456     1.99477     1.99506 
          1           1           1           1           1           1 
    1.99578     1.99591     1.99693     1.99763     1.99794     1.99808 
          1           1           1           1           1           1 
    1.99923     2.00065     2.00076     2.00198     2.00203     2.00204 
          1           1           1           1           1           1 
     2.0023     2.00242     2.00256     2.00356     2.00416     2.00467 
          1           1           1           1           1           1 
    2.00499     2.00593     2.00677      2.0078     2.00962     2.01046 
          1           1           1           1           1           1 
    2.01185     2.01305     2.01411     2.01622     2.01678     2.01706 
          1           1           1           1           1           1 
    2.01713      2.0177     2.01852     2.01928     2.02005     2.02029 
          1           1           1           1           1           1 
    2.02086     2.02131     2.02171     2.02234     2.02325     2.02371 
          1           1           1           1           2           1 
    2.02411     2.02475     2.02679      2.0277      2.0287     2.03229 
          1           1           1           1           1           1 
    2.03306     2.03327     2.03352     2.03353     2.03446     2.03598 
          1           1           1           1           1           1 
    2.03605     2.03673     2.03728     2.03772     2.03778     2.03824 
          1           1           1           1           1           1 
    2.03998     2.04014      2.0402     2.04059     2.04068     2.04094 
          1           1           1           1           1           1 
    2.04112     2.04141      2.0415     2.04166     2.04176     2.04273 
          1           1           1           1           1           1 
    2.04295       2.043     2.04329      2.0435     2.04419     2.04422 
          1           1           1           1           1           1 
    2.04479       2.045     2.04509     2.04813     2.04825     2.04934 
          1           1           1           1           1           1 
    2.05068     2.05181     2.05216     2.05223     2.05227     2.05385 
          1           1           1           1           1           1 
     2.0543      2.0568     2.05772     2.05783     2.05825     2.05836 
          1           1           1           1           1           1 
    2.06181     2.06199     2.06746     2.06812     2.06823     2.06915 
          1           1           1           1           1           1 
    2.06953     2.06997     2.07099     2.07166     2.07211     2.07247 
          1           1           1           1           1           1 
    2.07292     2.07299     2.07402     2.07627     2.07642     2.07663 
          1           1           1           1           1           1 
    2.07759     2.07774     2.08056     2.08142      2.0816     2.08187 
          1           1           1           1           1           1 
    2.08204     2.08223     2.08264     2.08412     2.08432     2.08657 
          1           1           1           1           1           1 
     2.0871     2.08769     2.08773     2.08861       2.089     2.08904 
          1           1           1           1           1           2 
     2.0894     2.09079     2.09149     2.09214     2.09254     2.09428 
          1           1           1           1           1           1 
    2.09432     2.09483     2.09522     2.09574     2.09648     2.09692 
          1           1           1           1           1           1 
    2.09782     2.09844     2.09862     2.09998     2.10025     2.10093 
          1           1           1           1           1           1 
    2.10196     2.10216     2.10221     2.10237     2.10245     2.10256 
          1           1           1           1           1           1 
    2.10286     2.10463     2.10477     2.10724     2.10914     2.10926 
          1           1           1           1           1           1 
    2.11049     2.11093     2.11147     2.11203     2.11585     2.11594 
          1           1           1           1           1           1 
    2.11786     2.12017     2.12047     2.12252     2.12262     2.12387 
          1           1           1           1           1           1 
    2.12455     2.12467     2.12618     2.12735     2.12803     2.12882 
          1           2           1           1           1           1 
    2.12975     2.13176     2.13215     2.13246      2.1325     2.13531 
          1           1           1           1           1           1 
    2.13606     2.13725     2.13731     2.13737     2.13982     2.14007 
          1           1           1           1           1           1 
    2.14026     2.14055     2.14067     2.14121      2.1415     2.14181 
          1           1           1           1           1           1 
    2.14266     2.14385     2.14431     2.14457     2.14566     2.14572 
          1           1           1           1           1           1 
    2.14697     2.14704     2.14743     2.14777     2.14779     2.14781 
          1           1           1           1           1           1 
    2.14786     2.14878     2.14967     2.15037     2.15092     2.15113 
          1           1           1           1           1           1 
     2.1513     2.15243     2.15246     2.15249     2.15344     2.15375 
          1           1           1           1           1           1 
    2.15428     2.15541     2.15545     2.15795     2.15845     2.15966 
          1           1           1           1           1           1 
    2.15992     2.16241     2.16358     2.16443     2.16445     2.16512 
          1           1           1           1           1           1 
    2.16539     2.16604     2.16611     2.16646     2.16736     2.16931 
          1           1           1           1           1           1 
    2.16944     2.16958     2.16981     2.17104     2.17127     2.17161 
          1           1           1           1           1           1 
    2.17284     2.17333     2.17351     2.17361     2.17473     2.17616 
          1           1           1           1           1           1 
    2.17674     2.17676     2.17692     2.17707     2.17714     2.17819 
          1           1           1           1           1           1 
    2.17905     2.17932     2.17979     2.18015      2.1804     2.18055 
          1           1           1           1           1           1 
    2.18157     2.18317     2.18463     2.18472     2.18603     2.18765 
          1           1           1           1           1           1 
    2.18788     2.18812     2.18837     2.18851     2.18929     2.19061 
          1           1           1           1           1           1 
    2.19144     2.19176     2.19327     2.19361     2.19477     2.19484 
          1           1           1           1           2           1 
    2.19485     2.19496     2.19533     2.19557     2.19558     2.19682 
          1           1           1           1           1           1 
    2.19706     2.19972     2.20015     2.20094     2.20165     2.20219 
          1           1           1           1           1           1 
    2.20344     2.20382     2.20429     2.20508      2.2052     2.20553 
          1           1           1           1           2           1 
    2.20609     2.20748     2.20766      2.2078     2.20799     2.21053 
          1           1           1           1           1           1 
     2.2111      2.2112     2.21149     2.21244     2.21348     2.21366 
          1           1           1           1           1           1 
    2.21382     2.21415     2.21416     2.21423     2.21484     2.21486 
          1           1           1           1           1           1 
    2.21504     2.21518     2.21589     2.21604     2.21631     2.21676 
          1           1           1           1           1           1 
    2.21683     2.21724     2.21922     2.22041     2.22111     2.22212 
          1           1           1           1           1           1 
    2.22341      2.2252     2.22547      2.2259     2.22636     2.22657 
          1           1           1           1           1           1 
    2.22688     2.22839      2.2284     2.22994     2.23041     2.23129 
          1           1           1           1           1           1 
    2.23174     2.23184     2.23219      2.2322     2.23248      2.2326 
          1           1           1           1           1           1 
    2.23281     2.23349     2.23387     2.23402     2.23416     2.23489 
          1           1           1           1           1           1 
    2.23668     2.23684       2.237     2.23743     2.23805     2.23875 
          1           1           1           1           1           1 
    2.23885      2.2392      2.2396     2.24001     2.24015     2.24028 
          1           1           1           1           1           1 
    2.24046     2.24057     2.24117     2.24146     2.24199     2.24275 
          1           1           1           1           1           1 
    2.24405     2.24436     2.24694     2.24749     2.24807     2.24814 
          1           1           1           1           1           1 
     2.2493     2.25022     2.25069     2.25094     2.25175     2.25365 
          1           1           1           1           1           1 
    2.25459     2.25577     2.25707     2.25791     2.25804     2.25825 
          1           1           1           1           1           1 
    2.25828     2.25833     2.25866     2.26198     2.26227     2.26259 
          1           1           1           1           1           1 
    2.26422     2.26487     2.26549     2.26555     2.26585      2.2661 
          1           1           1           1           1           1 
    2.26617     2.26701     2.26715     2.26734     2.26777       2.268 
          1           1           1           1           1           1 
    2.26813      2.2692     2.26938     2.26976     2.27162     2.27333 
          1           1           1           1           1           1 
    2.27396     2.27465     2.27563     2.27782     2.27836     2.27891 
          1           1           1           1           1           1 
    2.28037     2.28041     2.28084      2.2819     2.28304     2.28392 
          1           1           1           1           1           1 
     2.2844     2.28458     2.28493     2.28498     2.28525     2.28688 
          1           1           1           1           1           1 
    2.28709     2.28737     2.28784     2.28834     2.28898      2.2894 
          1           1           1           1           1           1 
    2.28947     2.29054     2.29305     2.29364     2.29432     2.29834 
          1           1           1           1           1           1 
    2.29842     2.29898     2.29904     2.29937     2.29956     2.29972 
          1           1           1           1           1           1 
    2.29975     2.30111     2.30152     2.30316     2.30461     2.30481 
          1           1           1           1           1           1 
    2.30562     2.30629     2.30863     2.30993     2.31088     2.31114 
          1           1           1           1           1           1 
    2.31182      2.3122     2.31292     2.31419     2.31449     2.31508 
          1           1           1           1           1           1 
    2.31575     2.31712     2.31909      2.3191     2.32155     2.32176 
          1           1           1           1           1           1 
      2.323     2.32612      2.3263     2.32635     2.32699     2.32705 
          1           1           1           1           1           1 
    2.32778     2.32881      2.3294     2.32953     2.33008     2.33039 
          1           1           1           1           1           1 
    2.33129     2.33251     2.33299     2.33315     2.33358     2.33419 
          1           1           1           1           1           1 
    2.33509     2.33553     2.33593     2.33657     2.33756     2.33773 
          1           1           1           1           1           1 
    2.33803     2.33813     2.33972     2.34034     2.34218     2.34232 
          1           1           1           1           1           1 
    2.34241     2.34309     2.34411     2.34488     2.34527     2.34624 
          1           1           1           1           1           1 
    2.34723     2.34727     2.35146     2.35158     2.35172     2.35183 
          1           1           1           1           1           1 
    2.35338     2.35411     2.35484     2.35504     2.35666     2.35805 
          1           1           1           1           1           1 
     2.3589     2.35953     2.35988     2.36051     2.36178     2.36286 
          1           1           1           1           1           1 
    2.36421     2.36436     2.36512     2.36522     2.36555     2.36649 
          1           1           1           1           1           1 
    2.36858     2.36951     2.36983     2.37147     2.37187     2.37203 
          1           1           1           1           1           1 
    2.37243     2.37258     2.37424     2.37428     2.37521     2.37565 
          1           1           1           1           1           1 
    2.37666     2.37711      2.3773     2.37834      2.3807     2.38076 
          1           1           1           1           1           1 
    2.38144     2.38146      2.3827     2.38297     2.38323     2.38415 
          1           1           1           1           1           1 
    2.38571     2.38618     2.38722     2.38725     2.38763     2.38846 
          1           1           1           1           1           1 
    2.38902     2.38992     2.39062     2.39088     2.39187     2.39196 
          1           1           1           1           1           1 
     2.3922     2.39252     2.39596     2.39656     2.39849     2.39903 
          1           1           1           1           1           1 
     2.3996      2.4002      2.4012     2.40143     2.40177     2.40455 
          1           1           1           1           1           1 
    2.40562     2.40602     2.40614     2.40812     2.40942     2.40974 
          1           1           1           1           1           1 
    2.40977     2.41007     2.41053     2.41069     2.41071     2.41122 
          1           1           1           1           1           1 
    2.41158     2.41186     2.41231     2.41237     2.41245     2.41273 
          1           1           1           1           1           1 
    2.41372     2.41384     2.41482     2.41572     2.41604     2.41634 
          1           1           1           1           1           1 
    2.41781     2.41855     2.41876     2.41977     2.42167      2.4222 
          1           1           1           1           1           1 
    2.42311      2.4248     2.42541     2.42546     2.42617     2.42917 
          1           1           1           1           1           1 
     2.4298     2.43087     2.43144     2.43178     2.43491     2.43546 
          1           1           1           1           1           1 
    2.43743      2.4375     2.43793     2.43859     2.43912     2.43979 
          1           1           2           1           1           1 
     2.4398     2.44084     2.44272     2.44306      2.4438     2.44391 
          1           1           1           1           1           1 
    2.44416      2.4444     2.44558     2.44596     2.44605     2.44778 
          1           1           1           1           1           1 
    2.44913      2.4497     2.44998      2.4502     2.45026     2.45153 
          1           1           1           1           1           1 
     2.4521     2.45356     2.45443     2.45478     2.45568     2.45634 
          1           1           1           1           1           1 
    2.45646     2.45709     2.45711     2.45746     2.45949     2.46245 
          1           1           1           1           1           1 
    2.46289     2.46334     2.46571     2.46774     2.46797       2.468 
          1           1           1           1           1           1 
    2.46818     2.46841     2.47132     2.47201     2.47554     2.47704 
          1           1           1           1           1           1 
    2.47751     2.47877      2.4824     2.48278     2.48459     2.48471 
          1           1           1           1           1           1 
    2.48485     2.48517     2.48545      2.4867     2.48678      2.4872 
          1           1           1           1           1           1 
    2.48741     2.48761     2.48891     2.48976     2.49035     2.49143 
          1           1           1           1           1           1 
    2.49197     2.49204     2.49247     2.49329     2.49412     2.49536 
          1           1           1           1           1           1 
    2.49639      2.4969     2.49734     2.49752      2.4985      2.4987 
          1           1           1           1           1           1 
    2.49872     2.49977     2.50128     2.50134     2.50221     2.50278 
          1           1           1           1           1           1 
    2.50283     2.50357     2.50507     2.50617     2.50648     2.50684 
          1           1           1           1           1           1 
    2.50714     2.50778     2.50846     2.50865     2.50988     2.51019 
          1           1           1           1           1           1 
    2.51028     2.51046     2.51246     2.51371      2.5139     2.51449 
          1           1           1           1           1           1 
     2.5174     2.51792     2.51793     2.51981     2.52011     2.52169 
          1           1           1           1           1           1 
    2.52177     2.52218     2.52266     2.52414     2.52427     2.52574 
          1           1           1           1           1           1 
    2.52813     2.52858     2.52929     2.52931     2.52979     2.53176 
          1           1           1           1           1           1 
    2.53218     2.53234     2.53277     2.53338     2.53565      2.5358 
          1           1           1           1           1           1 
    2.53615     2.53675     2.53697     2.53699     2.53764     2.53767 
          1           1           1           1           1           1 
    2.53796     2.53877     2.53968     2.54175     2.54294     2.54357 
          1           1           1           1           1           1 
    2.54687     2.54693     2.54745     2.55016     2.55055     2.55323 
          1           1           1           1           1           1 
    2.55544     2.55623     2.55774     2.55805     2.55816     2.55817 
          1           1           1           1           1           1 
    2.55877     2.55897     2.55965     2.56072      2.5627     2.56436 
          1           1           1           1           1           1 
    2.56494     2.56508     2.56518     2.56544     2.56591     2.56654 
          1           1           1           1           1           1 
    2.56657     2.56736     2.56743     2.56767     2.56886     2.56929 
          1           1           1           1           1           1 
    2.56931     2.57078     2.57134     2.57227     2.57273     2.57406 
          1           1           1           1           1           1 
    2.57524     2.57654     2.57793     2.57849     2.57856      2.5788 
          1           1           1           1           1           1 
     2.5789     2.57921     2.57925      2.5812     2.58147     2.58234 
          1           1           1           1           1           1 
    2.58251     2.58324      2.5842     2.58668     2.58725     2.58941 
          1           1           1           1           1           1 
    2.59111     2.59205     2.59258      2.5932     2.59335     2.59531 
          1           1           1           1           1           1 
    2.60058     2.60266      2.6032     2.60453      2.6061     2.60631 
          1           1           1           1           1           1 
    2.60676     2.60715     2.60766     2.60804     2.60965     2.60966 
          1           1           1           1           1           1 
    2.61025     2.61029     2.61112     2.61311     2.61428     2.61482 
          1           1           1           1           1           1 
    2.61543      2.6158     2.61619     2.61673     2.61721     2.61812 
          1           1           1           1           1           1 
    2.61813     2.61821     2.61835     2.61936     2.61968     2.62018 
          1           1           1           1           1           1 
    2.62072      2.6217     2.62391     2.62443      2.6246     2.62531 
          1           1           1           1           1           1 
    2.62539     2.62552     2.62692     2.62705     2.62983     2.63047 
          1           1           1           1           1           1 
    2.63093     2.63341     2.63442     2.63465     2.63589     2.63602 
          1           1           1           1           1           1 
    2.63603      2.6389     2.63951     2.63976     2.64337     2.64399 
          1           1           1           1           1           1 
    2.64497      2.6462     2.64632     2.64803     2.64827     2.64888 
          1           1           1           1           1           1 
    2.64923     2.64937     2.65158     2.65193     2.65224     2.65263 
          1           1           1           1           1           1 
    2.65321     2.65348     2.65433     2.65442     2.65475     2.65543 
          1           1           1           1           1           1 
    2.65753     2.65776     2.65866     2.65878     2.65997     2.66192 
          1           1           1           1           1           1 
    2.66201     2.66273     2.66288      2.6631      2.6641     2.66438 
          1           1           1           1           1           1 
     2.6665     2.66671     2.66708     2.66709      2.6673      2.6676 
          1           1           1           1           1           1 
    2.66835     2.67413     2.67498     2.67502     2.67564     2.67605 
          1           1           1           1           1           1 
    2.67627     2.67691     2.67854     2.67935     2.68327     2.68458 
          1           1           1           1           1           1 
    2.68542     2.68605     2.68705     2.68936     2.68986     2.69293 
          1           1           1           1           1           1 
    2.69345     2.69369     2.69517      2.6952     2.69552     2.69583 
          1           1           1           1           1           1 
    2.69635     2.69757     2.69854     2.70017     2.70141     2.70167 
          1           1           1           1           1           1 
    2.70276     2.70345     2.70694     2.70829     2.70954     2.70988 
          1           1           1           1           1           1 
     2.7099     2.71055     2.71129      2.7131     2.71398     2.71524 
          1           1           1           1           1           1 
    2.71649     2.71675     2.71719      2.7177     2.71784     2.71799 
          1           1           1           1           1           1 
    2.71831     2.71857     2.71931     2.71957     2.72024     2.72048 
          1           1           1           1           1           1 
    2.72139     2.72145     2.72148     2.72202     2.72303     2.72364 
          1           1           1           1           1           1 
    2.72367     2.72436     2.72448     2.72456     2.72463     2.72612 
          1           1           1           1           1           1 
    2.72666     2.72672     2.72755     2.72782     2.72891     2.73093 
          1           1           1           1           1           1 
    2.73102     2.73107     2.73147     2.73243     2.73253      2.7338 
          1           1           1           1           1           1 
    2.73494     2.73503     2.73747     2.73781     2.73871     2.73925 
          1           1           1           1           1           1 
    2.73964     2.73991     2.74005     2.74029     2.74071     2.74146 
          1           1           1           1           1           1 
    2.74151     2.74237     2.74241     2.74411     2.74445     2.74465 
          1           1           1           1           1           1 
    2.74491     2.74621     2.74656     2.74718     2.74828     2.74862 
          1           1           1           1           1           1 
    2.74881     2.74892     2.75186       2.752     2.75221     2.75431 
          1           1           1           1           1           1 
    2.75458     2.75532     2.75554     2.75763     2.75807      2.7594 
          1           1           1           1           1           1 
     2.7613     2.76272      2.7631     2.76316     2.76385     2.76405 
          1           1           1           1           1           1 
    2.76447     2.76584     2.76661      2.7692     2.76932     2.76993 
          1           1           1           1           1           1 
    2.77006     2.77117     2.77126     2.77264     2.77283     2.77285 
          1           1           1           1           1           1 
    2.77527     2.77553     2.77638      2.7772     2.77807      2.7786 
          1           1           1           1           1           1 
     2.7802     2.78255     2.78308     2.78553     2.78564     2.78632 
          2           1           1           1           1           1 
    2.78691     2.78727     2.78844     2.78896     2.78939     2.79117 
          1           1           1           1           1           1 
    2.79135     2.79188     2.79272      2.7932     2.79341     2.79348 
          1           1           1           1           1           1 
    2.79395     2.79497     2.79572     2.79916     2.79955     2.79975 
          1           1           1           1           1           1 
    2.80001     2.80184     2.80431     2.80469     2.80491     2.80633 
          1           1           1           1           1           1 
    2.80641     2.81056     2.81189     2.81572     2.81597     2.81601 
          2           1           1           1           1           1 
    2.81874     2.81883     2.82092     2.82231     2.82301     2.82345 
          1           1           1           1           1           1 
    2.82369     2.82498     2.82528     2.82543     2.82561     2.82618 
          1           2           1           1           1           1 
    2.82753     2.83144      2.8327     2.83294     2.83704     2.83739 
          1           1           1           1           1           1 
    2.83791     2.83814      2.8388     2.83898     2.83929     2.84031 
          1           1           1           1           1           1 
    2.84065     2.84169     2.84416     2.84494     2.84497     2.84568 
          1           1           1           1           1           1 
    2.84797     2.84818     2.84914      2.8493     2.85107     2.85145 
          1           1           1           1           1           1 
    2.85264     2.85275      2.8533      2.8542     2.85711     2.85847 
          1           1           1           1           1           1 
    2.85893     2.85926     2.85969     2.85999     2.86019     2.86045 
          1           1           1           1           1           1 
     2.8606     2.86102     2.86159     2.86328      2.8673     2.86823 
          1           1           1           1           1           1 
    2.86977     2.87339     2.87496     2.87539     2.87606     2.87622 
          1           1           1           1           1           1 
    2.87625     2.87676     2.87691     2.87692     2.87694     2.87747 
          1           1           1           1           1           1 
    2.87799      2.8785     2.87972     2.88142     2.88594     2.88682 
          1           1           1           1           1           1 
    2.88774     2.89188     2.89246     2.89266     2.89276     2.89688 
          1           1           1           1           1           1 
    2.89724     2.89772     2.89993     2.90072     2.90152     2.90453 
          1           1           1           1           1           1 
    2.90547     2.90556     2.90679     2.90686     2.90774     2.90833 
          1           1           1           1           1           1 
     2.9089      2.9094     2.90995     2.91041     2.91217     2.91475 
          1           1           1           1           1           1 
    2.91622     2.91803     2.91876     2.91935     2.91975     2.92006 
          1           1           1           1           1           1 
    2.92078     2.92119     2.92151     2.92207     2.92253     2.92645 
          1           1           1           1           1           1 
     2.9267     2.92793     2.92832     2.92883     2.92905     2.93026 
          1           1           1           1           1           1 
    2.93316      2.9333     2.93392     2.93497     2.93829     2.93907 
          1           1           1           1           1           1 
    2.94269     2.94354     2.94438     2.94592     2.94645     2.94722 
          1           1           1           1           1           1 
    2.94738     2.94785     2.95051     2.95084     2.95146     2.95157 
          1           1           1           1           1           1 
    2.95204      2.9546     2.95545      2.9557     2.95588     2.95666 
          1           1           1           1           1           1 
    2.95681        2.96     2.96132     2.96169       2.962     2.96283 
          1           1           1           1           1           1 
    2.96476      2.9656     2.96796     2.96841     2.97211     2.97362 
          1           1           2           1           1           1 
    2.97483     2.97546     2.97595     2.97604     2.97706     2.98053 
          1           1           1           1           1           1 
    2.98131     2.98166      2.9867     2.98708     2.98782     2.98813 
          1           1           1           1           1           1 
    2.98852     2.98921     2.99097     2.99304     2.99461     2.99561 
          1           1           1           1           1           1 
    2.99582     2.99772     2.99794     2.99855     3.00121     3.00473 
          1           1           1           1           1           1 
    3.00539     3.00572     3.00593     3.00785     3.00797     3.00878 
          1           1           1           1           1           1 
    3.01527     3.01629      3.0194     3.01941     3.02083     3.02175 
          1           1           1           1           1           1 
    3.02633      3.0265     3.02873     3.03125     3.03156     3.03344 
          1           1           1           1           1           1 
    3.03398     3.03714     3.03748     3.04039     3.04298     3.04385 
          1           1           1           1           1           1 
    3.04552     3.04893     3.04982     3.05052       3.052     3.05283 
          1           1           1           1           1           1 
    3.05415     3.05466     3.05704     3.05705     3.05726     3.05739 
          1           1           1           1           1           1 
     3.0618     3.06318     3.06425     3.06621     3.06665     3.06747 
          1           1           1           1           1           1 
    3.06795     3.06886     3.06967     3.07025     3.07172     3.07246 
          1           1           1           1           1           1 
    3.07257     3.07328     3.07367     3.07379     3.07449     3.07624 
          1           1           1           1           1           1 
    3.07628      3.0794     3.07989     3.08022     3.08034     3.08372 
          1           1           1           1           1           1 
    3.08374      3.0854     3.08548      3.0855     3.08856      3.0886 
          1           1           1           1           1           1 
    3.09008      3.0911     3.09398     3.09444     3.09541     3.09555 
          1           1           1           1           1           1 
    3.09633     3.09757     3.09833      3.0997     3.09982     3.10053 
          1           1           1           1           1           1 
    3.10166     3.10548     3.10868     3.11014     3.11576     3.11577 
          1           1           1           1           1           1 
    3.11691     3.11735     3.11867     3.12013     3.12029     3.12159 
          1           1           1           1           1           1 
    3.12288     3.12426     3.12456      3.1248     3.12723     3.12748 
          1           1           1           1           1           1 
    3.12839     3.12976     3.13051     3.13463     3.13647     3.14131 
          1           1           1           1           1           1 
    3.14351     3.14491     3.14613     3.14853     3.15144      3.1517 
          1           1           1           1           1           1 
    3.15189     3.15379     3.15387     3.15673     3.15675     3.15884 
          1           1           2           1           1           1 
    3.16081     3.16209     3.16279     3.16324     3.16475      3.1671 
          1           1           1           1           1           1 
    3.16772     3.16879     3.16965     3.16966     3.17793     3.17967 
          1           1           1           1           1           1 
    3.17972     3.18061     3.18361     3.18778       3.188     3.18815 
          1           1           1           1           1           1 
    3.18885     3.18979     3.18985     3.19156     3.19222     3.19266 
          1           1           1           1           1           1 
    3.19295       3.193     3.19411     3.19484     3.19588     3.19636 
          1           1           1           1           1           1 
    3.19803     3.19898     3.19948     3.20085     3.20215     3.20465 
          1           1           1           1           1           1 
    3.20518     3.20771     3.20806     3.20887     3.20921     3.20967 
          1           1           1           1           1           1 
    3.21079      3.2118     3.21232     3.21286      3.2147     3.21578 
          1           1           1           1           1           1 
    3.21683     3.21715     3.21832     3.21923     3.21985     3.22054 
          1           1           1           1           1           1 
    3.22713     3.22766     3.22829     3.23192     3.23493     3.23512 
          1           1           1           1           1           1 
    3.23882     3.24189     3.24297     3.24436     3.24577     3.24667 
          1           1           1           1           1           1 
    3.24671     3.24737     3.24784     3.24798       3.248     3.24999 
          1           1           1           1           1           1 
    3.25276     3.25496     3.25541     3.25971     3.26052     3.26087 
          1           1           1           1           1           1 
    3.26103     3.26391     3.26596     3.26856     3.26952     3.27228 
          1           1           1           1           1           1 
    3.27265     3.27568     3.27642     3.27896     3.28025     3.28101 
          1           1           1           1           1           1 
    3.28373     3.28643     3.28903     3.28992     3.29016     3.29117 
          1           1           1           1           1           1 
    3.29206      3.2941     3.29552     3.29747     3.30183     3.30329 
          1           1           1           1           1           1 
    3.30414     3.30598     3.30627     3.31003      3.3105     3.31294 
          1           1           1           1           1           1 
    3.31835     3.31886     3.32391     3.32505     3.32522     3.32618 
          1           1           1           1           1           1 
    3.32776      3.3285     3.32969     3.33096     3.33109     3.33145 
          1           1           1           1           1           1 
    3.33399     3.33534     3.33688     3.33747     3.34156     3.34233 
          1           1           1           1           1           1 
    3.34242     3.34271     3.34517     3.34556     3.34564     3.34612 
          1           1           1           1           1           1 
    3.34685     3.34808     3.35084     3.35183     3.35435     3.35508 
          1           1           1           1           1           1 
    3.35529     3.35836     3.35837     3.36043     3.36086     3.36111 
          1           1           1           1           1           1 
    3.36391     3.36421     3.36477     3.36502     3.36517     3.36746 
          1           1           1           1           1           1 
    3.36829     3.37095     3.37282     3.37568     3.37594     3.37668 
          1           1           1           1           1           1 
    3.37908     3.38023     3.38265     3.38335     3.38469     3.38605 
          1           1           1           1           1           1 
    3.38662     3.38756     3.38999     3.39276     3.39365     3.39389 
          1           1           1           1           1           1 
    3.39431     3.39949     3.40219     3.40302     3.40352     3.40761 
          1           1           1           1           1           1 
    3.41721     3.41771     3.41785     3.42123     3.42367     3.42597 
          1           1           1           1           1           1 
     3.4275     3.43161     3.43533     3.43726     3.44156     3.44232 
          1           1           1           1           1           1 
    3.44386     3.44746     3.44747     3.44894     3.44983     3.45177 
          1           1           1           1           1           1 
     3.4534      3.4547     3.45518     3.45562     3.45826     3.45986 
          1           1           1           1           1           1 
    3.46084     3.46727     3.46854     3.46904     3.47511     3.47836 
          1           1           1           1           1           1 
    3.47887     3.48015     3.48142     3.48288     3.48613     3.48728 
          1           1           1           1           1           1 
    3.48746     3.48865     3.49169     3.49181     3.49415     3.49689 
          1           1           1           1           1           1 
    3.50115     3.50277     3.50314     3.50633     3.50785     3.50889 
          1           1           1           1           1           1 
    3.51316     3.51337     3.51654     3.52266     3.52494     3.52651 
          1           1           1           1           1           1 
    3.52698     3.52837     3.52916     3.53285     3.53433     3.53449 
          1           1           1           1           1           1 
    3.53726     3.54121     3.54427     3.54431     3.54463     3.54811 
          1           1           1           1           1           1 
    3.54913     3.54983     3.55194     3.55422     3.55754     3.55923 
          1           1           1           1           1           1 
    3.55929     3.56383     3.56499     3.56508     3.56917     3.56962 
          1           1           1           1           1           1 
    3.57096     3.57959     3.58238     3.58442     3.58567     3.58927 
          1           1           1           1           1           1 
    3.58932     3.58958     3.59029     3.59466     3.60138      3.6048 
          1           1           1           1           1           1 
    3.60854     3.60928     3.61042     3.61044     3.61171     3.61609 
          1           1           1           1           1           1 
    3.61716     3.62545     3.62551     3.62575     3.63004     3.63107 
          1           1           1           1           1           1 
    3.63642     3.63694     3.63985     3.64669     3.65006     3.65065 
          1           1           1           1           1           1 
    3.65856     3.65952     3.66346     3.67029     3.67175     3.67602 
          1           1           1           1           1           1 
    3.67851      3.6816     3.68745     3.69062     3.69091     3.69883 
          1           1           1           1           1           1 
    3.70091     3.70305     3.70397     3.70517     3.71286     3.71619 
          1           1           1           1           1           1 
    3.71685     3.72202     3.73093     3.73321     3.73526     3.74029 
          1           1           1           1           1           1 
    3.74068     3.74205     3.74245     3.74803     3.76201     3.76771 
          1           1           1           1           1           1 
    3.77637     3.77638     3.77744     3.77927      3.7809     3.78327 
          1           1           1           1           1           1 
    3.78368     3.78747     3.78849     3.79117     3.79877     3.80018 
          1           1           1           1           1           1 
    3.80807     3.80942     3.81315     3.81855     3.81976     3.82312 
          1           1           1           1           1           1 
    3.82606     3.82769     3.83102      3.8361     3.83744     3.84058 
          1           1           1           1           1           1 
    3.84321     3.84676       3.848     3.85612      3.8613     3.86946 
          1           1           1           1           1           1 
    3.87043     3.87722     3.87928     3.88114     3.88523     3.88853 
          1           1           1           1           1           1 
    3.89438     3.89455     3.89524     3.89928     3.90079     3.90173 
          1           1           1           1           1           1 
    3.90972     3.91163     3.91551     3.91687     3.91808     3.92211 
          1           1           1           1           1           1 
    3.92906      3.9392     3.94031     3.94134     3.94584      3.9499 
          1           1           1           1           1           1 
    3.95773     3.97202     3.97616     3.97767     3.98328     3.98687 
          1           1           1           1           1           1 
    3.99088     3.99913     3.99979     4.00157     4.00717     4.00765 
          1           1           1           1           1           1 
    4.00788     4.00967     4.01131     4.02366     4.02767     4.03663 
          1           1           1           1           1           1 
    4.03709     4.04562     4.05059     4.05993     4.06446     4.06533 
          1           1           1           2           1           1 
    4.08258     4.08902     4.09095     4.09466     4.09491      4.0965 
          1           1           1           1           1           1 
    4.09781     4.11733     4.12079     4.12114     4.12699      4.1298 
          1           1           1           1           1           1 
    4.13851     4.14046     4.14261      4.1503     4.15232     4.15792 
          1           1           1           1           1           1 
    4.16046     4.16937     4.17342     4.18096     4.18538     4.19653 
          1           1           1           1           1           1 
    4.20089     4.20154     4.20693      4.2231      4.2285     4.23098 
          1           1           1           1           1           1 
      4.235       4.237     4.23945     4.24743     4.24963     4.26038 
          1           1           1           1           1           1 
    4.29884     4.32518     4.33704     4.35927     4.36538     4.37605 
          1           1           1           1           1           1 
    4.38343     4.38719     4.41211     4.42238     4.42603      4.4333 
          1           1           1           1           1           1 
     4.4464     4.44895     4.44984     4.45248     4.45704     4.46671 
          1           1           1           1           1           1 
    4.52898     4.55624     4.58921     4.60532     4.61931     4.62198 
          1           1           1           1           1           1 
    4.64041     4.64149      4.7361     4.74234     4.77632     4.88056 
          1           1           1           1           1           1 
    4.90564     4.92285      4.9336     5.22174     5.32681 
          1           1           1           1           1 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(geno_subset<span class="sc">$</span>rs1861_C)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   0    1    2 
  15  398 3551 </code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">glm</span>(PHENOTYPE <span class="sc">~</span> rs1861_C, <span class="at">data =</span> geno_subset, <span class="at">family =</span> gaussian)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = PHENOTYPE ~ rs1861_C, family = gaussian, data = geno_subset)

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.05238    0.09486   0.552    0.581    
rs1861_C     0.97382    0.04943  19.703   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for gaussian family taken to be 1.005963)

    Null deviance: 4376.1  on 3963  degrees of freedom
Residual deviance: 3985.6  on 3962  degrees of freedom
AIC: 11277

Number of Fisher Scoring iterations: 2</code></pre>
</div>
</div>
<p>The P value is 2e-16.</p>
<ol start="2" type="i">
<li>How would you interpret the beta coefficient from this regression?</li>
</ol>
<p>#Because the p value is small, there is an association between having the C allele and an increased expression of the phenotype.The positive value of the coefficient indicates that each additional C allele at this position increases the odds of the individual having a more intensely expressed phenotype for this trait.</p>
<ol start="3" type="i">
<li>Plot the scatterplot of phenotype versus the genotype of SNP rs1861. Add the regression line to the plot.</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a> geno_range <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>   <span class="at">rs1861_C =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">2</span>, <span class="at">length.out =</span> <span class="dv">100</span>)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a> )</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a> geno_range<span class="sc">$</span>predicted_prob <span class="ot">&lt;-</span> <span class="fu">predict</span>(model, <span class="at">newdata =</span> geno_range, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>count_data <span class="ot">&lt;-</span> geno_subset <span class="sc">%&gt;%</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(rs1861_C, PHENOTYPE) <span class="sc">%&gt;%</span></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>(), <span class="at">.groups =</span> <span class="st">"drop"</span>)</span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span> (count_data, <span class="at">n=</span><span class="dv">15</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3,944 × 3
   rs1861_C PHENOTYPE count
      &lt;int&gt;     &lt;dbl&gt; &lt;int&gt;
 1        0    -1.18      1
 2        0    -1.03      1
 3        0    -0.975     1
 4        0    -0.707     1
 5        0    -0.602     1
 6        0    -0.560     1
 7        0    -0.306     1
 8        0     0.215     1
 9        0     0.230     1
10        0     0.236     1
11        0     0.462     1
12        0     0.760     1
13        0     0.819     1
14        0     1.10      1
15        0     1.71      1
# ℹ 3,929 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>p1<span class="ot">=</span><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> count_data,</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> rs1861_C, <span class="at">y =</span> PHENOTYPE, <span class="at">size =</span> count),</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"blue"</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> geno_range,</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> rs1861_C, <span class="at">y =</span> predicted_prob),</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"red"</span>,</span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="fl">1.2</span></span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_size_continuous</span>(<span class="at">range =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">10</span>)) <span class="sc">+</span></span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Linear Regression: PHENOTYPE ~ Genotype"</span>,</span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Genotype (0/1/2)"</span>,</span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Phenotype "</span>, <span class="at">size =</span> <span class="st">"Count"</span></span>
<span id="cb31-18"><a href="#cb31-18" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb31-19"><a href="#cb31-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-20"><a href="#cb31-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">xlim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.5</span>, <span class="fl">2.5</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">2.7</span>, <span class="fl">5.5</span>)) <span class="sc">+</span></span>
<span id="cb31-21"><a href="#cb31-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb31-22"><a href="#cb31-22" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb31-23"><a href="#cb31-23" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb31-24"><a href="#cb31-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-25"><a href="#cb31-25" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(p1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="assignment_1_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="st">"./02_activities/data/p1_plotA1.png"</span>, <span class="at">plot =</span> p1, <span class="at">width =</span> <span class="dv">7</span>, <span class="at">height =</span> <span class="dv">5</span>, <span class="at">dpi =</span> <span class="dv">300</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ol start="4" type="i">
<li>Convert the genotype coding for rs1861 to recessive coding.</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>geno_subset_rec <span class="ot">&lt;-</span> geno_subset  </span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>geno_subset_rec[, <span class="dv">7</span><span class="sc">:</span><span class="fu">ncol</span>(geno_subset_rec)] <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lapply</span>(geno_subset[, <span class="dv">7</span><span class="sc">:</span><span class="fu">ncol</span>(geno_subset)], <span class="cf">function</span>(x) <span class="fu">ifelse</span>(x <span class="sc">==</span> <span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">0</span>))</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(geno_subset_rec)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     FID    IID   PAT   MAT   SEX PHENOTYPE rs1861_C
   &lt;int&gt; &lt;char&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;     &lt;num&gt;    &lt;num&gt;
1:     1  A2002     0     0     1   1.85385        1
2:     2  A2003     0     0     1   2.08264        1
3:     3  A2004     0     0     1   2.73871        1
4:     4  A2005     0     0     1   1.34114        1
5:     6  A2007     0     0     1   2.38297        1
6:     7  A2008     0     0     1   1.51430        1</code></pre>
</div>
</div>
<ol start="22" type="a">
<li>Conduct a linear regression to test the association between the recessive-coded rs1861 and the phenotype. What is the p-value?</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">glm</span>(PHENOTYPE <span class="sc">~</span> rs1861_C, <span class="at">data =</span> geno_subset_rec, <span class="at">family =</span> gaussian)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)         </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = PHENOTYPE ~ rs1861_C, family = gaussian, data = geno_subset_rec)

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.99231    0.04945   20.07   &lt;2e-16 ***
rs1861_C     1.00754    0.05224   19.29   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for gaussian family taken to be 1.009733)

    Null deviance: 4376.1  on 3963  degrees of freedom
Residual deviance: 4000.6  on 3962  degrees of freedom
AIC: 11292

Number of Fisher Scoring iterations: 2</code></pre>
</div>
</div>
<p>The p-value is 2e-16.</p>
<ol start="6" type="i">
<li>Plot the scatterplot of phenotype versus the recessive-coded genotype of rs1861. Add the regression line to the plot.</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>geno_range <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>   <span class="at">rs1861_C =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">length.out =</span> <span class="dv">100</span>)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a> )</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a> geno_range<span class="sc">$</span>predicted_prob <span class="ot">&lt;-</span> <span class="fu">predict</span>(model, <span class="at">newdata =</span> geno_range, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>count_data <span class="ot">&lt;-</span> geno_subset_rec <span class="sc">%&gt;%</span></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(rs1861_C), <span class="sc">!</span><span class="fu">is.na</span>(PHENOTYPE)) <span class="sc">%&gt;%</span></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(rs1861_C, PHENOTYPE) <span class="sc">%&gt;%</span></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>(), <span class="at">.groups =</span> <span class="st">"drop"</span>)</span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(count_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3,944 × 3
   rs1861_C PHENOTYPE count
      &lt;dbl&gt;     &lt;dbl&gt; &lt;int&gt;
 1        0    -2.01      1
 2        0    -1.94      1
 3        0    -1.18      1
 4        0    -1.14      1
 5        0    -1.03      1
 6        0    -1.03      1
 7        0    -1.02      1
 8        0    -0.975     1
 9        0    -0.974     1
10        0    -0.831     1
# ℹ 3,934 more rows</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>p2<span class="ot">=</span><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> count_data,</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> rs1861_C, <span class="at">y =</span> PHENOTYPE, <span class="at">size =</span> count),</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"blue"</span></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> geno_range,</span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> rs1861_C, <span class="at">y =</span> predicted_prob),</span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"red"</span>,</span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="fl">1.2</span></span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_size_continuous</span>(<span class="at">range =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">10</span>)) <span class="sc">+</span></span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb39-15"><a href="#cb39-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Linear Regression: PHENOTYPE ~ Genotype"</span>,</span>
<span id="cb39-16"><a href="#cb39-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Genotype (0/1)"</span>,</span>
<span id="cb39-17"><a href="#cb39-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Phenotype "</span>, <span class="at">size =</span> <span class="st">"Count"</span></span>
<span id="cb39-18"><a href="#cb39-18" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb39-19"><a href="#cb39-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">xlim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.5</span>, <span class="fl">1.5</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">2.7</span>, <span class="fl">5.5</span>)) <span class="sc">+</span></span>
<span id="cb39-20"><a href="#cb39-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb39-21"><a href="#cb39-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-22"><a href="#cb39-22" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(p2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="assignment_1_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="st">"./02_activities/data/p2_plotA1.png"</span>, <span class="at">plot =</span> p2, <span class="at">width =</span> <span class="dv">7</span>, <span class="at">height =</span> <span class="dv">5</span>, <span class="at">dpi =</span> <span class="dv">300</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ol start="7" type="i">
<li>Which model fits better? Justify your answer.</li>
</ol>
<p>The additive model fits better for this SNP. The AIC value for the additive model (11277) is slightly lower than the AIC value for the recessive model (11292) which indicates a better fit. In addition, the additive model shows that the aa genotype has phenotypic values less than 1.0 with only an n=15. When using recessive coding, the “0” includes heterozygotes which pushes that phenotypic frequency much higher than in the additive model. This could be inflating the influence of the aa genotype by combining it with the heterozygotes which have a higher phenotypic frequency when viewed through the additive model. It also underestimates the influence of the Aa genotype which, when seen in the additive model, does have higher phenotypic values than the aa genotype. When observing the linear regression line, the recessive model indicates that having aa or Aa genotype is associated with a 0 phenotype value and a genotype of AA is associated with a ~0.5 phenotype value. In contrast, the additive model shows that heterozygotes have an increased risk compared to aa homozygotes and AA homozygotes have a phenotype value of approximately 2. This shows a gradual increase in risk compared to the recessive model that potentially underestimates the influence of the Aa genotype.</p>
</section>
<section id="criteria" class="level3">
<h3 class="anchored" data-anchor-id="criteria">Criteria</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Criteria</th>
<th>Complete</th>
<th>Incomplete</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Data Inspection</strong></td>
<td>Correct sample/SNP counts and variable type identified.</td>
<td>Missing or incorrect counts or variable type.</td>
</tr>
<tr class="even">
<td><strong>Allele Frequency Estimation</strong></td>
<td>Correct allele and minor allele frequencies computed.</td>
<td>Frequencies missing or wrong.</td>
</tr>
<tr class="odd">
<td><strong>Hardy–Weinberg Equilibrium Test</strong></td>
<td>Correct PLINK command and p-value extraction in R.</td>
<td>PLINK command or extraction incorrect/missing.</td>
</tr>
<tr class="even">
<td><strong>Genetic Association Test</strong></td>
<td>Correct regressions, plots, coding, and interpretation.</td>
<td>Regression, plots, or interpretation missing/incomplete.</td>
</tr>
</tbody>
</table>
</section>
<section id="submission-information" class="level3">
<h3 class="anchored" data-anchor-id="submission-information">Submission Information</h3>
<p>📌 Please review our <a href="https://github.com/UofT-DSI/onboarding/blob/main/onboarding_documents/submissions.md">Assignment Submission Guide</a> for detailed instructions on how to format, branch, and submit your work. Following these guidelines is crucial for your submissions to be evaluated correctly.</p>
<section id="note" class="level4">
<h4 class="anchored" data-anchor-id="note">Note:</h4>
<p>If you like, you may collaborate with others in the cohort. If you choose to do so, please indicate with whom you have worked with in your pull request by tagging their GitHub username. Separate submissions are required.</p>
<hr>
</section>
<section id="submission-parameters" class="level4">
<h4 class="anchored" data-anchor-id="submission-parameters">Submission Parameters</h4>
<ul>
<li><p>Submission Due Date: <code>11:59 PM – 16/03/2026</code></p></li>
<li><p>Branch name for your repo should be: <code>assignment-1</code></p></li>
<li><p>What to submit for this assignment:</p>
<ul>
<li>Populate this Quarto document (<code>assignment_1.qmd</code>).</li>
<li>Render the document with Quarto: <code>quarto render assignment_1.qmd</code>.</li>
<li>Submit both <code>assignment_1.qmd</code> and the rendered HTML file <code>assignment_1.html</code> in your pull request.</li>
</ul></li>
<li><p>What the pull request link should look like for this assignment: <code>https://github.com/&lt;your_github_username&gt;/gen_data/pull/&lt;pr_id&gt;</code></p>
<ul>
<li>Open a private window in your browser. Copy and paste the link to your pull request into the address bar. Make sure you can see your pull request properly. This helps the technical facilitator and learning support team review your submission easily.</li>
</ul></li>
</ul>
<hr>
<p>Checklist:</p>
<ul>
<li>Created a branch with the correct naming convention.</li>
<li>Ensured that the repository is public.</li>
<li>Reviewed the PR description guidelines and adhered to them.</li>
<li>Verified that the link is accessible in a private browser window.</li>
<li>Confirmed that both <code>assignment_1.qmd</code> and <code>assignment_1.html</code> are included in the pull request.</li>
</ul>
<p>If you encounter any difficulties or have questions, please don’t hesitate to reach out to our team via our Slack help channel. Our technical facilitators and learning support team are here to help you navigate any challenges.</p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>